# Generated by Django 4.2.1 on 2024-10-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_gameresult_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameresult",
            name="ai_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="player_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player_two",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
