# Generated by Django 4.2.1 on 2024-10-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_gameresult_ai_model_alter_gameresult_player_two"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameresult", old_name="ai_model", new_name="ai_model2",
        ),
        migrations.AddField(
            model_name="gameresult",
            name="ai_model1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
