# Generated by Django 4.2.1 on 2024-10-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_rename_ai_model_gameresult_ai_model2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameresult",
            name="player_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player_one",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
